-- |
-- Module      : Crypto.PubKey.ECC.DH
-- License     : BSD-style
-- Maintainer  : Vincent Hanquez <vincent@snarc.org>
-- Stability   : experimental
-- Portability : unknown
--
-- Elliptic curve Diffie Hellman
module Crypto.PubKey.ECC.DH (
    Curve,
    PublicPoint,
    PrivateNumber,
    SharedKey (..),
    generatePrivate,
    calculatePublic,
    getShared,
    getShared',
) where

import Crypto.Error (
    CryptoError (..),
    CryptoFailable (..),
    throwCryptoError,
 )
import Crypto.Number.Generate (generateMax)
import Crypto.Number.Serialize (i2ospOf_)
import Crypto.PubKey.DH (SharedKey (..))
import Crypto.PubKey.ECC.Prim (isPointValid, pointMul)
import Crypto.PubKey.ECC.Types (
    Curve,
    Point (..),
    PrivateNumber,
    PublicPoint,
    common_curve,
    curveSizeBits,
    ecc_g,
    ecc_n,
 )
import Crypto.Random.Types

-- | Generating a private number d.
generatePrivate :: MonadRandom m => Curve -> m PrivateNumber
generatePrivate curve = generateMax n
  where
    n = ecc_n $ common_curve curve

-- | Generating a public point Q.
calculatePublic :: Curve -> PrivateNumber -> PublicPoint
calculatePublic curve d = q
  where
    g = ecc_g $ common_curve curve
    q = pointMul curve d g

-- | Generating a shared key using our private number and
--   the other party public point.
--
-- This raises the 'Crypto.Error.CryptoError' that 'getShared'' reports.  Use
-- 'getShared'' where the failure has to be handled.
getShared :: Curve -> PrivateNumber -> PublicPoint -> SharedKey
getShared curve db qa = throwCryptoError $ getShared' curve db qa

-- | Generating a shared key using our private number and the other party
--   public point, reporting a rejected point instead of raising.
--
-- The public point comes from the other party, so it is checked to be on the
-- curve first: the curve equation is what confines the result to the group our
-- private number was chosen for, and multiplying a point that does not satisfy
-- it lands in whatever group that point generates instead, which may be small
-- enough to recover the private number from.  Such a point is reported as
-- 'CryptoError_PointCoordinatesInvalid'.
--
-- Being on the curve is not by itself membership of the subgroup generated by
-- the base point; see 'isPointValid' for what the check does and does not
-- establish.
--
-- An exchange that yields the point at infinity, and so has no x coordinate to
-- derive the key from, is reported as 'CryptoError_ScalarMultiplicationInvalid'.
getShared' :: Curve -> PrivateNumber -> PublicPoint -> CryptoFailable SharedKey
getShared' curve db qa
    | not (isPointValid curve qa) = CryptoFailed CryptoError_PointCoordinatesInvalid
    | otherwise = case pointMul curve db qa of
        Point x _ -> CryptoPassed $ SharedKey $ i2ospOf_ ((nbBits + 7) `div` 8) x
        PointO -> CryptoFailed CryptoError_ScalarMultiplicationInvalid
  where
    nbBits = curveSizeBits curve
